### ISSUE TITLE
群晖运行jd_bean_sign.js出错

### ISSUE THREAD

**Issue by smilingpoplar** [lxk0301/scripts#159]
下载JD_DailyBonus.js失败，被墙？downFile()中能否加个参数，强制使用cdn地址下载？

❗️京豆签到, 错误!
RequestError: connect ECONNREFUSED 0.0.0.0:443
    at ClientRequest.<anonymous> (/scripts/node_modules/download/node_modules/got/index.js:182:22)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by lxk0301** [comment]
之前的控制是action下载git的链接，其他环境可能没有科学上网，就下载的是cdn的资源，我猜测你用的群晖应该是拿cdn的链接去下载的

**Comment by smilingpoplar** [comment]
对，用cdn链接可以下载。我提交了个pull request

**Comment by lxk0301** [comment]
@smilingpoplar 难道之前群晖下载的链接是第一个需要科学上网的原因？

**Comment by smilingpoplar** [comment]
对，因为要配置JD_COOKIE环境变量啊

**Comment by lxk0301** [comment]
@smilingpoplar 我懂了。你docker也跑第一个判断了。

**Comment by iouAkira** [comment]
> 对，因为要配置JD_COOKIE环境变量啊，根据代码就下了第一个

不清楚你这边用的是哪个docker镜像，能看docker images 看一下你用的镜像ID么，我昨天上午因为签到报错，又更新一版。还有就是，如果这下载错误是因为网络问题，那git pull应该也拉不到代码才对，pull.log里面应该也都是报错了看一下这个文件呢。

**Comment by smilingpoplar** [comment]
@iouAkira 
REPOSITORY                             TAG                 IMAGE ID            CREATED             SIZE
akyakya/jd_scripts                     latest              547b82b79470        23 hours ago        114MB
