### ISSUE TITLE
jd_bean_sign签到错误

### ISSUE THREAD

**Issue by husx** [lxk0301/scripts#193]
akyakya/jd_scripts  家用NAS docker环境
这个的意思是raw.githubusercontent.com无法访问吗？
```
🔔京豆签到, 开始!

❗️京豆签到, 错误!
RequestError: getaddrinfo ENOTFOUND raw.githubusercontent.com
    at ClientRequest.<anonymous> (/scripts/node_modules/download/node_modules/got/index.js:182:22)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

🔔京豆签到, 结束! 🕛 1.464 秒
```

**Comment by iouAkira** [comment]
@husx https://github.com/lxk0301/scripts/issues/159#issue-726804907

**Comment by lxk0301** [comment]
添加新的环境变量

CDN_JD_DAILYBONUS

**Comment by husx** [comment]
感谢，在docker-compose.yml中的environment里添加变量成功
`- CDN_JD_DAILYBONUS=true`
