### ISSUE TITLE
docker版的jd_bean_sign.js，零点自动签的时候报错，手动执行就正常，是什么情况，大佬

### ISSUE THREAD

**Issue by jjss520** [lxk0301/scripts#236]
开始京东账号1  京豆签到

替换变量完毕
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'request'
Require stack:
- /root/JD_DailyBonus.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /root/JD_DailyBonus.js:2442:23
    at nobyda (/root/JD_DailyBonus.js:2451:5)
    at Object.<anonymous> (/root/JD_DailyBonus.js:103:15)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/root/JD_DailyBonus.js' ]
}
京东签到脚本执行异常:Error: Command failed: node JD_DailyBonus.js >> result.txt
internal/modules/cjs/loader.js:968
  throw err;
  ^

Error: Cannot find module 'request'
Require stack:
- /root/JD_DailyBonus.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /root/JD_DailyBonus.js:2442:23
    at nobyda (/root/JD_DailyBonus.js:2451:5)
    at Object.<anonymous> (/root/JD_DailyBonus.js:103:15)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/root/JD_DailyBonus.js' ]
}

这是日志，但我手动在容器里执行命令，就正常签到，这是什么问题

**Comment by iouAkira** [comment]
如果用的 docker方法一的话，拉一下最新镜像启动应该就没啥问题了，因为签到脚本js文件是下载到了～目录，在～目录下找不到request依赖

**Comment by jjss520** [comment]
pull不了镜像，可以直接在容器里手动安装request模块来解决吗

**Comment by iouAkira** [comment]
@jjss520 可以，容器里面直接 cd ～ && npm install request

**Comment by vay1314** [comment]
@iouAkira docker能否增加一个参数变量控制清除日志呢，现在运行多了想看最新日志得往下翻很长

**Comment by iouAkira** [comment]
@vay1314 嗯，可以，不过在自定义my_crontab_list.sh 加一个定时任务定时删除也可以实现

**Comment by notget** [comment]
请教一下，我的是群晖，使用方法一(注册表下载之后直接导入json文件)，也是完全一样的报错。试过重新删除映象再下载，今天0点后还是一样的报错。

请教一下应该如何操作，因本人是小白，不太明白其中原理，有比较通俗易懂的小白操作步骤最好。谢谢了

**Comment by zhjcreator** [comment]
> 请教一下，我的是群晖，使用方法一(注册表下载之后直接导入json文件)，也是完全一样的报错。试过重新删除映象再下载，今天0点后还是一样的报错。
> 
> 请教一下应该如何操作，因本人是小白，不太明白其中原理，有比较通俗易懂的小白操作步骤最好。谢谢了

ssh连接群晖

![QQ图片20201030002910](https://user-images.githubusercontent.com/55911606/97603006-f5467380-1a46-11eb-8a20-ed9c2b0463bc.png)
sudo docker exec -i -t  容器名字 sh
cd ～ && npm install request

**Comment by notget** [comment]
> > 请教一下，我的是群晖，使用方法一(注册表下载之后直接导入json文件)，也是完全一样的报错。试过重新删除映象再下载，今天0点后还是一样的报错。
> > 请教一下应该如何操作，因本人是小白，不太明白其中原理，有比较通俗易懂的小白操作步骤最好。谢谢了
> 
> ssh连接群晖
> 
> ![QQ图片20201030002910](https://user-images.githubusercontent.com/55911606/97603006-f5467380-1a46-11eb-8a20-ed9c2b0463bc.png)
> sudo docker exec -i -t 容器名字 sh
> cd ～ && npm install request

好的，谢谢大佬！
